arb-dir: localization
output-dir: lib/generated/l10n
template-arb-file: app_en.arb
output-localization-file: localization.dart
untranslated-messages-file: untranslated-messages.txt
nullable-getter: false
synthetic-package: false # needed after flutter_gen is deprecated: https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
