// Regenerates integration_test/all_test.dart — the single-entrypoint aggregator
// that runs Bull.init() once, then every integration test file's
// main(isInitialized: true). On the Linux desktop device the app can be
// launched only once per `flutter test` invocation, so the whole suite must run
// through one file; this script keeps that file in sync with what's on disk so
// nobody has to hand-edit it (or silently forget to).
//
// The output is a generated build artifact: it is gitignored and regenerated on
// every `make integration-test`. Do not commit or hand-edit it.
//
// Run via: fvm dart run tools/gen_all_test.dart
import 'dart:io';

// Files matching *_test.dart that must NOT be aggregated: the generated file
// itself, plus any test with no callable main(isInitialized:) (e.g. payjoin is
// commented out and needs funded testnet wallets).
//
// get_paid_backup_roundtrip_test.dart is authored-but-CI-only: it exercises the
// Get Paid money path against the app-process DI graph, but the live startup
// timers/blocs make an app-process pump non-deterministic in the aggregated
// suite. The deterministic money-path gate is the domain-layer round-trip
// (test/features/get_paid_settings/get_paid_backup_wire_roundtrip_test.dart);
// this file is kept for a dedicated CI job with a per-test relay-only harness.
const skip = {
  'all_test.dart',
  'payjoin_test.dart',
  'get_paid_backup_roundtrip_test.dart',
  // Dedicated fake/live Bullnym round-trip. It resets metadata tables and must
  // run in its own app process so the aggregate's shared state stays intact.
  'wallet_metadata_backup_roundtrip_test.dart',
  // SPEC-PP-01: same app-process non-determinism as the backup round-trip; the
  // deterministic Donation Page gates are the L0 usecase/cubit suites.
  'payment_page_lifecycle_test.dart',
  // SPEC-POS-01: same app-process non-determinism; the deterministic Point of
  // Sale gates are the L0 usecase/cubit suites.
  'pos_lifecycle_test.dart',
  // SPEC-INV-01: same app-process non-determinism; the deterministic Invoices
  // gates are the L0 usecase/cubit suites.
  'invoices_lifecycle_test.dart',
  // S-REAL-PROD-LIVE-NOPAY: production Bullnym/Nostr + real seed fixtures.
  // This is an explicit external lane only; never include it in the default
  // aggregate integration run.
  'get_paid_live_nopay_test.dart',
  // S-REAL-PROD-PAGE102-FUNDED: MOVES REAL FUNDS, coordinator-driven through a
  // handshake directory. Explicit external lane only; never aggregate it.
  'get_paid_page102_funded_test.dart',
  // S-REAL-PROD-POS103-FUNDED: MOVES REAL FUNDS, coordinator-driven through a
  // handshake directory. Explicit external lane only; never aggregate it.
  'get_paid_pos103_funded_test.dart',
  // S-REAL-PROD-LA101-FUNDED: MOVES REAL FUNDS, coordinator-driven through a
  // handshake directory. Explicit external lane only; never aggregate it.
  'get_paid_la101_funded_test.dart',
  // S-REAL-PROD-BTCPAY100-FUNDED: MOVES REAL FUNDS (on-chain BTC), drives the
  // real SamRock pairing with a run-time credential, coordinator-driven through
  // a handshake directory. Explicit external lane only; never aggregate it.
  'get_paid_btcpay100_funded_test.dart',
  // SPEC-BTCPAY100-PAIRING: deterministic no-pay pairing prerequisites +
  // redaction proof. App-process lifecycle spec; run via the explicit lane
  // (non-deterministic in the single-process aggregate, like the others above).
  'get_paid_btcpay100_pairing_test.dart',
  // S-REAL-PROD-BTCPAY100-FUNDED (pair-only preserve): LIVE SamRock pairing
  // against production that persists paired state for a later funded run.
  // Explicit external lane only; never aggregate it.
  'get_paid_btcpay100_pair_only_test.dart',
  // qa_matrix/* needs the fork-only qa_matrix_engine workspace package, which
  // is not wired into pubspec.yaml on this overlay (see the overlay NOTES) —
  // exclude the whole subtree from the aggregate rather than let it fail to
  // resolve.
  'qa_matrix_generative_test.dart',
  'qa_matrix_recovery_test.dart',
  'qa_matrix_smoke_test.dart',
};

void main() {
  final files =
      Directory('integration_test')
          .listSync()
          .whereType<File>()
          .map((f) => f.uri.pathSegments.last)
          .where((n) => n.endsWith('_test.dart') && !skip.contains(n))
          .toList()
        ..sort();

  if (files.isEmpty) {
    stderr.writeln(
      'gen_all_test: no *_test.dart files found in integration_test/',
    );
    exit(1);
  }

  final alias = {
    for (final f in files) f: f.substring(0, f.length - '_test.dart'.length),
  };

  final b = StringBuffer()
    ..writeln(
      '// GENERATED by tools/gen_all_test.dart — do not edit or commit.',
    )
    ..writeln('// Regenerated on every `make integration-test`.')
    ..writeln("import 'package:bb_mobile/main.dart';")
    ..writeln("import 'package:flutter_test/flutter_test.dart';");
  for (final f in files) {
    b.writeln("import '$f' as ${alias[f]};");
  }
  b
    ..writeln()
    ..writeln('Future<void> main() async {')
    ..writeln('  TestWidgetsFlutterBinding.ensureInitialized();')
    ..writeln('  await Bull.init();')
    ..writeln();
  for (final f in files) {
    b.writeln('  await ${alias[f]}.main(isInitialized: true);');
  }
  b.writeln('}');

  File('integration_test/all_test.dart').writeAsStringSync(b.toString());
  stdout.writeln(
    'gen_all_test: wired ${files.length} files -> integration_test/all_test.dart',
  );
}
