name = "radion"
description = "A sleek, modern blog theme."
tags = ["SEO", "search", "accessible"]
license = "MIT"
homepage = "https://github.com/micahkepe/radion"
min_version = "0.20.0"
demo = "https://micahkepe.com/radion/"

# Any variable that can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
radion_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://www.bullbitcoin.com", name = "Bull Bitcoin"},
]
codeblock = true
github = "https://github.com/your-github-link"

[author]
authors = ["ethicnology"]
homepage = "https://example.com"

