name: Analyze

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        analyze_mode:
          - { name: "Warnings fatal, Infos allowed", mode: "--no-fatal-infos", allow_failure: false }
          - { name: "Infos fatal, Warnings allowed", mode: "--no-fatal-warnings", allow_failure: false }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: make clean
      - run: make deps
      - run: make build-runner
      - run: make l10n
      
      - name: "${{ matrix.analyze_mode.name }}"
        run: flutter analyze ${{ matrix.analyze_mode.mode }}
        continue-on-error: ${{ matrix.analyze_mode.allow_failure }}
