name: Build

on:
  pull_request:
    branches:
      - main
      - develop
      
env:
  APP_NAME: BULL

jobs:
  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - run: rustup target add aarch64-apple-ios

    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        architecture: x64

    - run: make clean
    - run: make deps
    - run: make build-runner
    - run: make l10n

    - run: cp .env.template .env

    - name: Build no-codesign release
      run: flutter build ios --release --no-codesign
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}_ios
        path: build/ios/iphoneos/Runner.app
